<?php
// export-report.php
require_once 'config.php';
requireLogin();

if (!canViewReports()) {
    header("Location: dashboard.php");
    exit();
}

$start_date = $_GET['start_date'] ?? date('Y-m-01');
$end_date = $_GET['end_date'] ?? date('Y-m-d');

// Get visitors data
$query = "SELECT * FROM visitors WHERE DATE(CheckInTime) BETWEEN ? AND ? ORDER BY CheckInTime DESC";
$stmt = $pdo->prepare($query);
$stmt->execute([$start_date, $end_date]);
$visitors = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Get summary statistics
$stats_query = "SELECT 
    COUNT(*) as total_visitors,
    COUNT(CASE WHEN Status = 'Checked In' THEN 1 END) as active_visitors,
    COUNT(CASE WHEN Status = 'Checked Out' THEN 1 END) as checked_out_visitors,
    COUNT(CASE WHEN PWDStatus = 1 THEN 1 END) as pwd_visitors,
    COUNT(CASE WHEN Gender = 'Male' THEN 1 END) as male_visitors,
    COUNT(CASE WHEN Gender = 'Female' THEN 1 END) as female_visitors,
    COUNT(CASE WHEN HostAvailable = 0 THEN 1 END) as host_unavailable_visitors
    FROM visitors 
    WHERE DATE(CheckInTime) BETWEEN ? AND ?";
$stats_stmt = $pdo->prepare($stats_query);
$stats_stmt->execute([$start_date, $end_date]);
$stats = $stats_stmt->fetch(PDO::FETCH_ASSOC);

// Set headers for download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=knbs_visitor_report_' . date('Y-m-d') . '.csv');

// Create output stream
$output = fopen('php://output', 'w');

// Add BOM for UTF-8
fputs($output, $bom = (chr(0xEF) . chr(0xBB) . chr(0xBF)));

// Header row
fputcsv($output, ['KENYA NATIONAL BUREAU OF STATISTICS - VISITOR REPORT']);
fputcsv($output, ['Report Period:', $start_date . ' to ' . $end_date]);
fputcsv($output, ['Generated on:', date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated by:', $_SESSION['user_name'] . ' (' . $_SESSION['user_role'] . ')']);
fputcsv($output, []); // Empty row

// Summary statistics
fputcsv($output, ['SUMMARY STATISTICS']);
fputcsv($output, ['Total Visitors', $stats['total_visitors']]);
fputcsv($output, ['Active Visitors', $stats['active_visitors']]);
fputcsv($output, ['Checked Out Visitors', $stats['checked_out_visitors']]);
fputcsv($output, ['PWD Visitors', $stats['pwd_visitors']]);
fputcsv($output, ['Male Visitors', $stats['male_visitors']]);
fputcsv($output, ['Female Visitors', $stats['female_visitors']]);
fputcsv($output, ['Host Unavailable Cases', $stats['host_unavailable_visitors']]);
fputcsv($output, []); // Empty row

// Visitor details header
fputcsv($output, ['DETAILED VISITOR RECORDS']);
fputcsv($output, [
    'Badge Number',
    'Visitor Name',
    'Gender',
    'ID Type', 
    'ID Number',
    'Phone Number',
    'Organization',
    'Purpose of Visit',
    'Host Name',
    'Host Available',
    'Visitor Message',
    'PWD Status',
    'Has Luggage',
    'Luggage Number',
    'Check-in Time',
    'Check-out Time',
    'Visit Duration',
    'Status',
    'Badge Returned',
    'Admitting Officer',
    'Check-out Officer',
    'Visitor Feedback'
]);

// Visitor data
foreach ($visitors as $visitor) {
    // Calculate duration
    $duration = 'N/A';
    if ($visitor['CheckOutTime']) {
        $checkin = new DateTime($visitor['CheckInTime']);
        $checkout = new DateTime($visitor['CheckOutTime']);
        $interval = $checkin->diff($checkout);
        $duration = $interval->format('%hh %im');
    }
    
    fputcsv($output, [
        $visitor['BadgeNumber'],
        $visitor['FullName'],
        $visitor['Gender'],
        $visitor['IDType'],
        $visitor['IDNumber'],
        $visitor['PhoneNumber'] ?: '',
        $visitor['Organization'] ?: '',
        $visitor['PurposeOfVisit'],
        $visitor['HostName'] ?: '',
        $visitor['HostAvailable'] ? 'Yes' : 'No',
        $visitor['VisitorMessage'] ?: '',
        $visitor['PWDStatus'] ? 'Yes' : 'No',
        $visitor['HasLuggage'] ? 'Yes' : 'No',
        $visitor['LuggageNumber'] ?: '',
        date('Y-m-d H:i', strtotime($visitor['CheckInTime'])),
        $visitor['CheckOutTime'] ? date('Y-m-d H:i', strtotime($visitor['CheckOutTime'])) : '',
        $duration,
        $visitor['Status'],
        $visitor['BadgeReturned'] ? 'Yes' : 'No',
        $visitor['AdmittingOfficer'],
        $visitor['CheckOutOfficer'] ?: 'N/A',
        $visitor['Feedback'] ?: ''
    ]);
}

fclose($output);
exit();
?>